version: '3.8'

services:
    dev-db:
        image: postgres:13
        ports:
            - 5434:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: hQ8yyTb4TqxxDMQ
            POSTGRES_DB: nest
        networks:
            - ggps
        volumes:
            - postgres-data:/var/lib/postgresql/data

    nest-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 9000:9000
        environment:
            DATABASE_URL: postgres://postgres:hQ8yyTb4TqxxDMQ@dev-db:5432/nest
        depends_on:
            - dev-db
        networks:
            - ggps
        volumes:
            - .:/usr/src/app
        command: npm run start:dev

networks:
    ggps:

volumes:
    postgres-data:
